services:
  backend:
    image: node:16-alpine3.16
    expose:
      - 8000
    entrypoint: npm run dev
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ".:/app/"
  
  reverse-proxy-nginx:
    image: nginx:1.24.0-alpine
    depends_on: [backend]
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"

  reverse-proxy-httpd:
    image: httpd:2.4.57-alpine
    depends_on: [backend]
    ports:
      - 3001:3001
    stdin_open: true
    tty: true
    volumes:
      - "./httpd.conf:/usr/local/apache2/conf/httpd.conf"